# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Plucene-SearchEngine-Index-RSS
version:      0.01
version_from: lib/Plucene/SearchEngine/Index/RSS.pm
installdirs:  site
requires:
    Plucene::SearchEngine::Index:  1.1
    XML::RSS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
